logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG
